Prepare for React 19
JustFly1984/react-google-maps-api pull request #3382
Opened 2024-10-06 17:34 UTC by memark

This PR updates the code to eliminate some type problems with React 19 RC.

- Use `React.JSX` instead of global `JSX.`
- Use `React.ReactNode` instead of `React.ReactChild`

2024-10-07 16:02 UTC, JustFly1984 requested changes
Please, instead on prefixing React. everywhere, just import it on top of the file

import type { JSX } from 'react'

2024-10-08 17:10 UTC, memark commented
Sure thing. Done!

2024-10-08 18:34 UTC, JustFly1984 approved these changes

2024-10-08 18:34 UTC, merged

2024-10-08 18:36 UTC, JustFly1984 commented
@memark thank you for your PR. merged. Will try to find the time to release new version soon. I guess it need to bump peerDependencies too for react@19. please create one more PR. PS there is more than one package.

2024-10-08 18:38 UTC, JustFly1984 commented
PS2: I'm going to bring some love to this package soon, gonna replace gatsby.js with Vite, and maybe publish docs on Vite too. So no point to update gatsbyjs.

2024-10-10 08:48 UTC, JustFly1984 commented
released 2.20.1

@memark if you want to help more, I have a branch upgrade, which I've used to release 2.20.0 and 2.20.1

We currently having issues with react-styleguidist, and it is refuses to start, I guess due to some esm/cjs inconsistencies.

I've spent yesteday to bring some love to the project, and half of today, but I have no time anymore. If you could fix styleguidist, or replace it with other docs, I would love to deploy it again. Else, I don't know then next time I will have time to bring more love to the project.

2024-10-12 19:35 UTC, memark commented
I tried giving it a little love, but got no further. No combination of downgrading the styleguidist or docgen packages helped at all. Neither did removing our styleguide config. I haven't worked with Rollup/Webpack in years, so this will be difficult for me.

Do you have any idea when `build:docs` worked the last time?

2024-10-17 19:55 UTC, brunocoelho commented
Thanks for giving this project some attention @JustFly1984. Your work here is very valuable. ❤️